'✨ Feature':
  - head-branch: ['^feature', 'feature']
'🐛 BugFix':
  - head-branch: ['^hotfix', 'hotfix', '^fix', 'fix']
'🔧 Refactor':
  - head-branch: ['^refactor', 'refactor']
'🧪 Test':
  - '**/*.{spec,test}.{js,jsx,ts,tsx}'
'📚 Docs':
  - '**/*.md'
'🎨 Html&css':
  - head-branch: ['^design', 'design']
  - '**/*.{html,css}'
'⚙️ Setting':
  - 'package-lock.json'
  - '.github/workflows/**'
'🌎 Deploy':
  - '^ci\/cd\s*:'
  - '^ci\s*:'
  - '^cd\s*:'
'📨 Api':
  - 'src/**/api/**'
