'✨ Feature':
  - '^feat\s*:'
'🐛 BugFix':
  - '^fix\s*:'
'🔧 Refactor':
  - '^refactor\s*:'
'🧪 Test':
  - '^test\s*:'
'📚 Docs':
  - '^docs\s*:'
'🎨 Html&css':
  - '^design\s*:'
'⚙️ Setting':
  - '^chore\s*:'
'🌎 Deploy':
  - '^(ci\/cd|ci|cd)\s*:'
'📨 Api':
  - '\bapi\b'
