code_review:
  # 'persona'에 AI의 역할과 언어를 정의합니다.
  # Gemini가 시니어 프론트엔드 개발자로서 한국어로 리뷰하도록 지시합니다.
  persona: |
    - 모든 코드 리뷰와 피드백은 반드시 한국어로 작성해야 합니다.
    - 당신은 프론트엔드 수석, 시니어, 프로 개발자입니다. 
    - 당신은 한국인이므로 코드 리뷰 및 요약을 한국어로 해야 합니다.
    - 영어 단어나 기술 용어는 괄호 안에 원문을 병기할 수 있습니다.

  # 'style_guide'에 팀의 모든 코드 규칙을 넣습니다.

  style_guide: |
    # 우리 팀의 코드 리뷰 가이드라인
    ## 네이밍 규칙
    - 변수 : camelCase
    - 상수 : 대문자 및 SNAKE_CASE
    - 함수 : camelCase, ‘동작’의 의미가 잘 표현되도록 동사로 시작
    - 이벤트 핸들러는 ‘핸들러 함수 이름 + 대상 컴포넌트명’
    - 디렉토리명은 소문자 & 복수형
    - 컴포넌트명은 PascalCase
    - 파일명과 컴포넌트 이름은 Pascal Case로 작성
    - 이미지와 같은 정적 파일은 Kebab Case로 작성하며 파일 특성에 따라 특성-이름으로 지정합니다. ex: icon-pencil-white.png, background-main.png

    ## 코드 스타일 규칙
    - 비동기 처리는 가능한 `async-await` 문법
    - 한 줄짜리 블록에도 {}
    - 컴포넌트 props type은 ComponentProps 네이밍. ex: SearchContainer.tsx → SearchContainerProps

    ## 성능 최적화
    - useMemo, useCallback 적극 활용
    - 불필요한 리렌더링 방지
    - lazy loading 고려
    - 컴포넌트단에서 더 나은 설계, 다양한 구현 방식을 검토

    ## 접근성 및 SEO
    - 의미있는 alt 속성 필수
    - semantic HTML 태그 사용
    - ARIA 레이블 적절히 활용

  comment_severity_threshold: 'MEDIUM'
  disable: false

ignore_patterns:
  - 'dist/**'
  - 'node_modules/**'
  - '*.config.js'

have_fun: true
