name: Label Sync

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/labels.yml'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      labels: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync GitHub Labels
        uses: yoshikouki/label-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/labels.yml
          delete_unmanaged_labels: true
