name: Label Sync

on:
  push:
    branches: [main, develop]
    paths: ['.github/labels.yml']
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml
      - name: Sync GitHub Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
