# 워크플로우의 이름
name: PR Labeler

# 워크플로우가 실행될 시점을 정의
on:
  # Pull Request가 열릴때, 편집될때 실행
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # GitHub Actions에서 코드를 체크아웃하는 표준 액션
      - name: Checkout Code
        uses: actions/checkout@v4

      # actions/labeler 액션을 사용하여 라벨링 작업을 수행
      - name: Add Labels to PR
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/workflows/labeler.yml
